### PR TITLE
Create lorgarr-plex.css

### PR DESCRIPTION
**Pull request by goldenpipes**
ha lorgarr...

prolly a lot left to do but hell if it dont look neat!

### CODE REVIEW

**Comment by gilbN** [comment]
Nice! 👍🏻, fix the name first :P

**Comment by goldenpipes** [comment]
i named it that on porpose hehe

**Comment by gilbN** [comment]
oh, lol. Yeah that makes sense :) Also can you add it to the readme and add some screenshots and  I'll merge :) Thanks

**Comment by goldenpipes** [comment]
donski i think

**Pull request merged**
