### PR TITLE
Added theme for utorrent

### PR DESCRIPTION
**Pull request by monkey-debugger**
based on rutorrent theme

utorrent theme:
image

aquamarine:
image

dark:
image

hotline:
image

organizr-dark:
image

plex:
image

space-gray:
image

### CODE REVIEW

**Comment by monkey-debugger** [comment]
Gotta make a few more changes

**Comment by monkey-debugger** [comment]
Ready for review/merge

**Comment by GilbN** [comment]
Hi. What can I use to test this? I installed utorrent but the default theme looks like this. 
Which version is that?

**Comment by monkey-debugger** [comment]
I'm guessing you're running Linux? The WebUI I shared is uTorrent on Windows. I didn't know they have separate WebUI's per platform until now.

**Comment by monkey-debugger** [comment]
Looks like they dropped support for linux ~8 years ago. They also seem to have dropped support for Mac OS ~4 years ago, but I'm not sure about that one? Maybe I should change the folder name to `utorrent-for-windows`?

**Comment by GilbN** [comment]
Do you have a link to the windows installer?

**Comment by monkey-debugger** [comment]
Sure! https://download-hr.utorrent.com/track/stable/endpoint/utorrent/os/windows

**Comment by GilbN** [comment]
And how to you apply the css? Haven't used utorrent in like 15 years

**Comment by GilbN** [comment]
Doesn't seem like the webui works for me. Clicking install doesn't do much. I got to be honest, uTorrent seem like a garbage torrent client. 
I recommend using qbittorrent or deluge, they don't have ads in their app. 
Sorry, not gonna merge this, People should use a FOSS torrent client instead ;)

**Pull request closed without merging**
