### PR TITLE
new theme options

### PR DESCRIPTION
**Pull request by Monklite**
I have added the OneDark color scheme well-known as the color scheme for Atom. It's pretty popular, so I figured I would add it in.

### CODE REVIEW

**Comment by Monklite** [comment]
Also edited the Jellyfin css to change the header color to `--modal-header-color` as well as the sidebar to match `--modal-bg-color`

**Comment by GilbN** [comment]
Thanks for the new theme option!

> Also edited the Jellyfin css to change the header color to `--modal-header-color` as well as the sidebar to match `--modal-bg-color`

What was wrong with the default blur on the side menu?

**Comment by Monklite** [comment]
> Thanks for the new theme option!
> 
> > Also edited the Jellyfin css to change the header color to `--modal-header-color` as well as the sidebar to match `--modal-bg-color`
> 
> What was wrong with the default blur on the side menu?

I don't mind it; however, the header color doesn't change at all with this theme unless I make those changes in `jellyfin-base.css`. The same issue exists with the new Dracula theme, the header color just persists from the default Jellyfin theme if that makes sense. Theme likes Plex behave differently because of the blur, gradients, etc. Perhaps you can take a look at that if you have the time?

**Comment by Monklite** [comment]
Also, once we figure out the next steps, I'll go ahead and compile screenshots for the theme to finalize the PR.

**Comment by GilbN** [comment]
> > Thanks for the new theme option!
> > > Also edited the Jellyfin css to change the header color to `--modal-header-color` as well as the sidebar to match `--modal-bg-color`
> > 
> > 
> > What was wrong with the default blur on the side menu?
> 
> I don't mind it; however, the header color doesn't change at all with this theme unless I make those changes in `jellyfin-base.css`. The same issue exists with the new Dracula theme, the header color just persists from the default Jellyfin theme if that makes sense. Theme likes Plex behave differently because of the blur, gradients, etc. Perhaps you can take a look at that if you have the time?
> 
> I'd say the sidebar change should for sure be added, but we need to figure out the header issue that exists with this theme and Dracula.

The header does change. It's partially transparent. 
chrome


firefox


https://github.com/GilbN/theme.park/blob/master/CSS/themes/jellyfin/jellyfin-base.css#L134


Did you follow these install instructions or just standard subfilter?
https://docs.theme-park.dev/themes/jellyfin/#setup

**Comment by Monklite** [comment]
> > > Thanks for the new theme option!
> > > > Also edited the Jellyfin css to change the header color to `--modal-header-color` as well as the sidebar to match `--modal-bg-color`
> > > 
> > > 
> > > What was wrong with the default blur on the side menu?
> > 
> > 
> > I don't mind it; however, the header color doesn't change at all with this theme unless I make those changes in `jellyfin-base.css`. The same issue exists with the new Dracula theme, the header color just persists from the default Jellyfin theme if that makes sense. Theme likes Plex behave differently because of the blur, gradients, etc. Perhaps you can take a look at that if you have the time?
> > I'd say the sidebar change should for sure be added, but we need to figure out the header issue that exists with this theme and Dracula.
> 
> The header does change. It's partially transparent.
> chrome
> 
> 
> firefox
> 
> 
> https://github.com/GilbN/theme.park/blob/master/CSS/themes/jellyfin/jellyfin-base.css#L134
> 
> Did you follow these install instructions or just standard subfilter?
> https://docs.theme-park.dev/themes/jellyfin/#setup

Oh. I was applying the style through nginx, not the app itself. I'll try it with that way.

**Comment by Monklite** [comment]
Yup, this works as expected doing it directly through Jellyfin. I'm just curious if you know why that is?  

Also, is it possible to fix the disparity between the rendering of firefox and chrome regarding the header? It's much better in Chrome, but I use Firefox

**Comment by Monklite** [comment]
Okay so I looked into it and saw the bit about how this has to be changed manually in Firefox by setting `layout.css.backdrop-filter.enabled` to true. I just did that and it works as expected.  

So now that we have figured that out, I don't at all mind if you discard my edit to `jellyfin-base.css`. What would you like me to do next for this PR? Screenshots for the docs?

**Comment by GilbN** [comment]
> Okay so I looked into it and saw the bit about how this has to be changed manually in Firefox by setting `layout.css.backdrop-filter.enabled` to true. I just did that and it works as expected.
> 
> So now that we have figured that out, I don't at all mind if you discard my edit to `jellyfin-base.css`. What would you like me to do next for this PR? Screenshots for the docs?

Great. Yes, screenshots would be great. And yeah you can just revert those jellyfin base changes. 
I also need to add a fallback for firefox on the sidemenu as I see its just transparent without backdrop filter enabled.
If you want to add that too, go ahead.

**Comment by GilbN** [comment]
> Yup, this works as expected doing it directly through Jellyfin. I'm just curious if you know why that is?
> 

iirc, the theme.park css gets loaded before the jellyfin css. They load some of it in the body not the head. So subfiltering the body would probably have worked just fine.

**Comment by Monklite** [comment]
Alright I'll roll that back.  

Also, just for giggles, I replaced `</head>` with `</body>` in the subfilter area for nginx and the same issue occurred, so I'm just gonna keep applying it through the app itself.

"I also need to add a fallback for firefox on the sidemenu as I see its just transparent without backdrop filter enabled."

Yeah that's something better suited for you than myself, I'm not much of a web dev at all.

**Comment by Monklite** [comment]
Do you think the theme can be merged before screenshots are taken? I'm still getting my services up and running to be honest, though I have a friend with a lot and he could possibly take the screenshots for me.

**Comment by Monklite** [comment]
And do you want me to make a tailored file for every service within the `themes` folder or is that done by you when themes are created? I noticed the current community themes do not have that yet.

**Comment by GilbN** [comment]
If you don't run that many themable services just screenshot the ones you run and I'll fix the rest. 

No, you just need to add it in the variables folder.

**Comment by Monklite** [comment]
> If you don't run that many themable services just screenshot the ones you run and I'll fix the rest.
> 
> No, you just need to add it in the variables folder.

Okay, how is it then invoked upon merging? Usually you just specify the theme in the `themes` folder which will link to the base file as well as its respective variable. Do I instead just specify two lines (the base file as well as the variable file) to bypass that for the time being?  

I'll get started on the screenshots. Expect one for Pi-Hole, Portainer, Gitea, and Grafana.

**Comment by Monklite** [comment]
Made some changes, where do you want the screenshots?

**Comment by Monklite** [comment]
Here are some screenshots:

Pi-Hole
Pi-Hole

Portainer
Portainer

Gitea
Gitea  

I'd save them locally for upload, not sure how long I'll keep them on imgur.

**Comment by GilbN** [comment]
> Here are some screenshots:
> 
> Pi-Hole
> Pi-Hole
> 
> Portainer
> Portainer
> 
> Gitea
> Gitea
> 
> I'd save them locally for upload, not sure how long I'll keep them on imgur.

Thanks. Github has them now. So you can just remove them from imgur if you want.

**Comment by GilbN** [comment]
I added "By Monklite" on the community page. If you dont want that let me know. 
https://docs.theme-park.dev/community-themes/

**Comment by MilesTEG1** [comment]
Hello, How can this new theme can be installed/used ?

**Comment by GilbN** [comment]
Depends on the install method. There are new installation docs.

**Pull request merged**
