### PR TITLE
Bazarr white login screen fix

### PR DESCRIPTION
**Pull request by Shadow58624**
### Please remember to add a before and after screenshot(s) on any css changes! 
Dark (Before)
image

Dark (After)
image

Aquamarine (Before)
image

Aquamarine (After)
image

### CODE REVIEW

**Comment by GilbN** [comment]
Thanks for the PR!

**Comment by Shadow58624** [comment]
No problem, you were the one that gave me the push I needed to learn git and contribute to a project I like very much. Thank you!

**Comment by 2021zxc** [comment]
> 没问题，是你给了我学习 git 所需的动力，并为我非常喜欢的项目做出了贡献。谢谢！

hi
The colors on the right and top are inconsistent with the background color v8.1.3
grafana8 1 3

**Comment by GilbN** [comment]
> > 没问题，是你给了我学习 git 所需的动力，并为我非常喜欢的项目做出了贡献。谢谢！
> 
> hi
> The colors on the right and top are inconsistent with the background color v8.1.3
> grafana8 1 3

Grafana is unsupported.  And why are you commenting an a Pull Request about bazarr?

**Pull request merged**
