### PR TITLE
Fix link-color var in unraid dark & hotline

### PR DESCRIPTION
**Pull request by SDS1337**
### Before

<br>

### CODE REVIEW

**Comment by sadstan** [comment]
Imho, it makes it difficult to read... 🤔

**Comment by SDS1337** [comment]
@sadstan In Hotline, yes it does. But I didn't set that color, I just fixed the variable 😅. It was doing nothing all this time.

Feel free to suggest a color for it that I can replace this one with, and I'll add that in the PR.

**Comment by GilbN** [comment]
Try the same color as accent-color-hover. I see dark.css has the same ussue

**Comment by SDS1337** [comment]
@GilbN Still ugly :P, but readable pretty much.

**Comment by GilbN** [comment]
> @GilbN Still ugly :P, but readable pretty much.
> 
> Should I add this or change it?

Hm, just set it to white. More readable that way.

**Pull request merged**
